engines:
  duplication:
    enabled: false # true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
    strings:
    - TODO
    - FIXME
    - HACK
    - BUG
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  stylelint:
    enabled: true

ratings:
  paths:
  - "**.js"
  - "**.md"
  - "**.css"
  - "**.less"
  - "**.scss"
