# Example comment.

version: 2

jobs:
  build:
   working_directory: ~/Area51
   docker:
     - image: node:latest
   parallelism: 4
   steps:
     - checkout
     - run:
         name: Install dependencies
         command: |
           yarn
           apt-get update
           apt-get install ocaml libelf-dev -y
           curl https://install.meteor.com/ | sh
           yarn global add npx
     - run:
         name: Prepare and lint code
         command: |
           meteor --version --allow-superuser
           mkdir -p $CIRCLE_TEST_REPORTS/reports
           npx eslint . --fix --format junit --output-file $CIRCLE_TEST_REPORTS/reports/eslint.xml
           npx stylelint **/*.less
     - run:
         name: Test code and produce coverage
         command: |
           yarn test
           yarn run report-coverage
