# Example comment.

version: 2

jobs:
  build:
   working_directory: ~/Area51
   docker:
     - image: node:latest
   steps:
     - checkout
     - run:
         name: Install dependencies
         command: yarn
     - run:
         name: Lint code
         command: |
           mkdir -p $CIRCLE_TEST_REPORTS/reports
           yarn run lint -- --format junit --output-file $CIRCLE_TEST_REPORTS/reports/eslint.xml
     - run:
         name: Build code
         command: yarn run build